spring:
  jpa:
    show-sql: false
    open-in-view: true
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    url: jdbc:postgresql://localhost:5432/aps
    username: user
    password: password

server.servlet:
  encoding:
    charset: UTF-8
    enabled: true
    force: true