
CREATE DATABASE aps
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Russian_Russia.1251'
    LC_CTYPE = 'Russian_Russia.1251'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

create table users
(
    id       bigint generated by default as identity
        constraint users_pkey
            primary key,
    name     varchar(255) not null
        constraint uk_3g1j96g94xpk3lpxl2qbl985x
            unique,
    password varchar(255) not null
);

alter table users
    owner to "user";

create table request
(
    id          bigint generated by default as identity
        constraint request_pkey
            primary key,
    created     timestamp default now(),
    description varchar(255) not null,
    status      integer      not null,
    author_id   bigint
        constraint fkroq2b37lskxf9a0tmen9h1g4m
            references users
            on delete cascade
);

alter table request
    owner to "user";

create table user_roles
(
    user_id bigint not null
        constraint fkhfh9dx7w3ubf1co1vdev94g3f
            references users
            on delete cascade,
    role    varchar(255),
    constraint uk_user_roles
        unique (user_id, role)
);

alter table user_roles
    owner to "user";